### ISSUE TITLE
Scene Issue

### ISSUE THREAD

**Issue by seanmccabe** [MindrustUK/Heatmiser-for-home-assistant#111]
Seem to be having an issue when I attempt to activate a scene.

I have the following script that creates a scene:

```
sequence:
          - service: scene.create
            data:
              scene_id: heating_off_auto
              snapshot_entities:
                - climate.home
          - delay:
              seconds: 2
          - service: input_boolean.turn_on
            entity_id: input_boolean.heating_paused
          - service: climate.turn_off
            target:
              entity_id: climate.home 
```

However, when I then call the service to apply the scene like so:

```
sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.heating_paused
          - service: scene.turn_on
            target: 
              entity_id: scene.heating_off_auto
```

I get the following errors in the logs:

_Heating On: Error executing script. Error for choose at pos 1: Entity climate.home does not support this service._
_Heating On: Choose at step 1: choice 1: Error executing script. Error for call_service at pos 2: Entity climate.home does not support this service._
_Error while executing automation automation.door_closed_turn_on_heating: Entity climate.home does not support this service._

All relates to the automation and then script that fired it. Not sue which service it is referring too, as when I call the scene service in dev it appears to work, and it is working in the background.
Maybe something the scene is trying to perform in the background to re-activate the scene this integration says it supports but doesn't?

If there is anymore info I can provide to work out this issue, let me know.
