### ISSUE TITLE
Bug: Climate state set to "Off" when using Hold feature.

### ISSUE THREAD

**Issue by Plawasan** [MindrustUK/Heatmiser-for-home-assistant#144]
I'm raising this here while I'm debating myself if this is an issue with Heatmiser or Powercalc.. 

I am using the Powercalc integration to create virtual power usage sensor for my floors - in principle it all works as expected, with one exception - when using the hold function on the thermostat then the heatmiser climate entity reports the following status:

![image](https://github.com/MindrustUK/Heatmiser-for-home-assistant/assets/73796046/6014b19d-f7f2-45a7-a7cd-32ed18adba0e)

Notice that hvac_action attribute is set to "heating" however the overall state of the entity is "off". 

This then causes an issue downstream in Powercalc, which is configured to look for the state of the attribute however it apparently also checks the state of the entity itself before it sets the power value:

```
powercalc:
  sensors:
    - entity_id: climate.living_room
      fixed:
        states_power:
          hvac_action|heating: 3100
```

I tested this by forcing the entity state (from "off" to "heat") and that gave me the expected result.

So my question is - should Heatmiser set the climate entity to "heat" when using hold or should powercalc ignore the overall state of the entity and only consider the attribute?
