### ISSUE TITLE
Clean up: Deprecated constants log error in Home Assistant 2024.1

### ISSUE THREAD

**Issue by jamespreedy** [MindrustUK/Heatmiser-for-home-assistant#154]
## Version of the custom_component

Latest version on HACS - 0d4905c

## Configuration

```yaml
Logger: homeassistant.components.climate.const
Source: helpers/deprecation.py:204
Integration: Climate (documentation, issues)
First occurred: 7:57:45 am (14 occurrences)
Last logged: 7:57:46 am

HVAC_MODE_HEAT was used from heatmiserneo, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please report it to the author of the 'heatmiserneo' custom integration
HVAC_MODE_HEAT_COOL was used from heatmiserneo, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT_COOL instead, please report it to the author of the 'heatmiserneo' custom integration
HVAC_MODE_OFF was used from heatmiserneo, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please report it to the author of the 'heatmiserneo' custom integration
SUPPORT_TARGET_TEMPERATURE was used from heatmiserneo, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'heatmiserneo' custom integration
SUPPORT_TARGET_TEMPERATURE_RANGE was used from heatmiserneo, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE_RANGE instead, please report it to the author of the 'heatmiserneo' custom integration


Logger: homeassistant.const
Source: helpers/deprecation.py:204
First occurred: 7:57:45 am (26 occurrences)
Last logged: 7:57:48 am

TEMP_CELSIUS was used from heatmiserneo, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'heatmiserneo' custom integration
TEMP_FAHRENHEIT was used from heatmiserneo, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.FAHRENHEIT instead, please report it to the author of the 'heatmiserneo' custom integration

```

## Describe the bug

See above logs - various constants used in the custom component will be depreciated in a future version of Home Assistant.
I appreciate this is something that everyone will see, but if I can help with any additional logs etc, please let me know - I'll be happy to help how I can.
