### ISSUE TITLE
Allow Hold On temperature in 0.5 increments

### ISSUE THREAD

**Issue by ocrease** [MindrustUK/Heatmiser-for-home-assistant#175]
The hold_on service expects the temperature to be an integer, but heatmiser allows increments of 0.5 degrees. I updated climate.py and services.yaml to allow float rather than int and used the HA Developer Tools to call the service with a x.5 temperature and it was accepted:

```
action: heatmiserneo.hold_on
data:
  hold_duration: "01:00:00"
  hold_temperature: 23.5
target:
  entity_id: climate.zone1
```

```
hvac_modes: off, heat
min_temp: 7
max_temp: 35
target_temp_step: 0.5
current_temperature: 21.5
temperature: 23.5
hvac_action: heating
low_battery: false
offline: false
standby: false
hold_on: true
hold_time: 0:56
hold_temp: 23.5
floor_temperature: 127.5
preheat_active: false
friendly_name: Zone1
supported_features: 385
```

It would be nice to remove the restriction requiring an integer. Happy to raise a pull request if that helps.
