### ISSUE TITLE
Hot water timer

### ISSUE THREAD

**Issue by BNWEIN** [MindrustUK/Heatmiser-for-home-assistant#199]
Hey

I am sorry if this isnt the place to ask for support. I am a little confused how the hot water timer works. I have a device called "Kitchen Timer". I want to configure a button, that when i press the button a 1 hour override runs on that timer to turn the hot water on for an hour, but i cannot for the life of me figure out how i would do that ?

Any help appreciated! 

thanks

**Comment by ocrease** [comment]
Hi @BNWEIN In order to set a timer override with a custom duration, you need to call the `heatmiserneo.timer_hold_on` action:

![image](https://github.com/user-attachments/assets/0d561327-8576-490d-88c4-cba781e31f02)

Or in YAML:
```
action: heatmiserneo.timer_hold_on
target:
  entity_id: switch.hot_water_heatmiser_neostat_v2_timer_override
data:
  hold_duration:
    hours: 1
    minutes: 0
    seconds: 0
```
If you want to cancel the hold, you would just call the standard `switch.turn_off` action.

How you call the service from a button is largely up to you and you can browse the Home Assistant forums for ideas. Here is a basic example that you could use. 

1. Create a [script ](https://www.home-assistant.io/integrations/script/) to call the service based on the current state (you can do it from the UI):

![image](https://github.com/user-attachments/assets/b0653e9d-02be-4ba9-b0ac-8ba2fef4d9bb)
This example uses a condition based on the `hold_active` sensor provided by the integration. When it is `on`, it calls the standard `switch.turn_off` service targeting the `timer_override` switch. Otherwise (eg when the hold is not active) it calls the `heatmiserneo.timer_hold_on` service with a 1 hour duration

2.  You can then create a button to display the hold state and call the script:
![image](https://github.com/user-attachments/assets/054bba08-9cd4-443e-842f-0d1805f7d476)

```
show_name: true
show_icon: true
type: button
tap_action:
  action: perform-action
  perform_action: script.hot_water_boost_toggle
  target: {}
entity: switch.hot_water_heatmiser_neostat_v2_timer_hold
name: Hot Water Boost
```

Note if you wanted to just turn on the boost and don't need the ability to turn it off, you don't need the script. Just call the service directly from the button `tap_action`.
