### ISSUE TITLE
Logging not working

### ISSUE THREAD

**Issue by ntompson** [MindrustUK/Heatmiser-for-home-assistant#20]
I've just successfully set up an integration for my two Heatmiser Neo stats using this great component. I can see my two thermostats and control the set point in HA.

But I'm not getting any logging. I've set up the following in my `configuration.yaml` file:
```yaml
logger:
  default: warning
  logs:
    homeassistant.components.flic: debug
    homeassistant.components.climate.heatmiserneo: debug
```
I'm not getting anything in the log at all, even though the `heatmiserneo` component seems to be working (mostly). By contrast, the `flic` component is producing logging messages, as expected.

Any ideas what might be wrong? I'm no expert (at all) on HA components, but the code looks like logging should do something...

**Comment by MindrustUK** [comment]
Try the following:

```# Debug logging for Heatmiser
logger:
  default: debug
  logs:
    homeassistant.components.climate.heatmiserneo: debug
```
That's producing debug output for me? Let me know how you get on.

**Comment by ntompson** [comment]
Thanks - that did work, but of course, it caused all components to generate debug logs, which gets rather noisy. With a bit more research, I've figured out that `custom_components` need a different naming format for logger. This works:
```yaml
logger:
  default: warning
  logs:
    homeassistant.components.flic: debug
    custom_components.heatmiserneo: debug
```
I would guess that this different format was because of a recent change to HA (who knows when), so it might be worth updating the read me.
