### ISSUE TITLE
HVAC Mode now only shows 'Heat'

### ISSUE THREAD

**Issue by Nick-Sills** [MindrustUK/Heatmiser-for-home-assistant#280]
I realize that this was a recent intentional change:
https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/255

However, this has now considerably impaired the usability of the HA Thermostat Card for Heatmiser thermostats, and makes the thermostats behave in a non standard way.

I noticed that one of the comments in support of the change was: 

> "Currently, the integration uses `HVACMode.OFF` when a thermostat is in standby. I think Home Assistant expects the device to be fully off in that case, but with the Heatmiser thermostats, *they are never truly off because they have frost protection*."  ." 

However, **most (if not all) thermostats have a Frost/Set-Back temperature setting. They all use an `hvac_mode` of `Off`, and `hvac_action` changes to `heating` if the temperature drops below the set-back threshold. Heatmiser thermostats are physically the same as every other thermostat, there's nothing special about the way they handle frost protection. 

What is different with Heatmiser, is the poorly designed Heatmiser App UI, and that shouldn't really be replicated in Home Assistant. 

**For reference, this includes other thermostats I use: Sonoff TRVZB, Daikin, Tado, and various no-name Chinese Zigbee thermostats across multiple HA instances.

This Heatmiser thermostat is `Off`, but the state `Heat`:

<img src="https://github.com/user-attachments/assets/dd9614d2-3b09-4bf4-8db7-5a38ad68f4ba" width="400">

Note:  The text 'Heat' is now permanent. It never changes.

Please consider restoring back `hvac_mode`  `Off` so that Heatmiser thermostats function consistently with other thermostats.. Perhaps it could be synced to preset `Away` if that satisfies the previous change?

**Comment by ocrease** [comment]
I'd like to know what functionality is impaired, could you share some screenshots of the Thermostat Card you are using? The screenshot you added was of an Entity Row (I think). 

You are correct that in the entity row the state is always Heat (unless you have a NeoStat HC), which I still think is correct. The developer docs for the [climate](https://developers.home-assistant.io/docs/core/entity/climate?_highlight=hvacmode.off#hvac-modes) entity state:

`HVACMode.HEAT | The device is set to heat to a target temperature.`

When the device is in Standby, that description is correct, the target temperature is the frost protection temperature. 

You should be looking at the HVAC Action (Idle in your screenshot) to see if the thermostat is heating or not. 

I found at least one other integration that deals with frost protection using a preset -> [Netatmo](https://github.com/home-assistant/core/blob/d5af542dd1fa4cda2b7e6870e205a17b79c845bb/homeassistant/components/netatmo/climate.py#L84)

In the thermostat card you don't have to show the hvac mode. 

![Image](https://github.com/user-attachments/assets/1a24770c-6e62-4d02-9613-3bf8f1a844ed)

I'm hesitant to change back to the old way. There were issues with the history charts not showing heating when the HVAC mode is off.

**Comment by Nick-Sills** [comment]
Hi @ocrease, Thanks for the quick reply. 

I understand that it's a bit of a longshot to revert, or modify, a change that is so recent, but I thought I'd ask anyway. :smile:

> I'd like to know what functionality is impaired, could you share some screenshots of the Thermostat Card you are using? 

Sorry, my bad, it isn't the Thermostat Card that I have a problem with.

 > When the device is in Standby, that description is correct, the target temperature is the frost protection temperature.

> The developer docs for the [climate](https://developers.home-assistant.io/docs/core/entity/climate?_highlight=hvacmode.off#hvac-modes) entity state:
> HVACMode.HEAT | The device is set to heat to a target temperature.

I guess that's the problem for me. It's in Frost/Fall-Back mode, not a normal operation 'heat' mode.   The thermostat doesn't heat to the frost setting. Is has a positive hysteresis, so it starts heating when it reaches the frost temperature and stops when 1 degree above. It's not the same. 

> I found at least one other integration that deals with frost protection using a preset -> [Netatmo](https://github.com/home-assistant/core/blob/d5af542dd1fa4cda2b7e6870e205a17b79c845bb/homeassistant/components/netatmo/climate.py#L84)

I could be wrong, but that looks like it has an `off` `hvac_action` as well as `heat`. 

I have a combination of underfloor water heating downstairs with Heatmiser thermostats, and radiators upstairs using Zigbee TRVs. The TRVs are also set to 12c Frost Protection, and they, like other thermostats I have at a different location, have both  `Heat` and `Off`  `hvac_modes`

Heating is being controlled by a Shelly Wall Panel x2 (with a 7" Rectangular Screen) in vertical mode. So I use entity cards to give a visual view of the total system. I do the same in my desktop HA dashboard as well.  You can just touch the entity to open the thermostat card, and it stops you accidentally swiping the temperature. 

The house is a holiday home in Ireland, currently empty and cold:

<img src="https://github.com/user-attachments/assets/4b1f8caa-5062-4e43-bcae-4835d00025be" width="400">


The house is so cold at the moment, that the upstairs TRVs have kicked into frost/damp protection with a 1 degree up hysteresis, and they remain 'Off'. My Tado system is the same at home.  

It will also look odd in the summer when the Heatmiser stats show 'Heat' when the system is Off (never going to heat). I know that I can ignore the word 'Heat' and look at 'Idle', but try saying that to my Wife, or rental guests when it's 25c outside. 😄 

My automations to change the `hvac_mode` for all climate entities to `off` when the house isn't occupied failed, so I had to change it for the Heatmiser stats. 

I know that I can use presets to achieve the same, but the go-to Climate automation actions, Climate 'Turn Off' & Climate 'Turn On' fail:

> Error: Entity climate.bedroom_downstairs does not support action climate.turn_off

If it can't be changed, I may have to create template climate entities going forward, to solve these problems, but I think I might have a problem syncing the `hvac_action`. 🤔  

Thanks for listening.

**Comment by ocrease** [comment]
Just so that we are on the same page, I think you have two issues:

1. Automations need to use a different service to set the preset rather than the hvac action. This should be easy to take care off but let me know if you need help.
2. A visual issue where thermostats from different integrations display different things. My suggestion here is to not rely on the standard climate entity row at all. Use something like the [multiple-entity-row](https://github.com/benct/lovelace-multiple-entity-row) and display exactly what you want.

![Image](https://github.com/user-attachments/assets/bfbdd3e8-faab-4b38-8ea2-75f530f98880)

**Comment by ocrease** [comment]
Out of interest, those thermostats upstairs that are off but heating (which looks odd to my eyes), if you look at the history graph, does it show that they have been heating (eg the orange shaded area under the graph)?

Also, why do you have all but one thermostat set to away? For the heatmiser stats, just set one to away and all will go to away. No need to set each one to standby.

Have you seen the [docs](https://mindrustuk.github.io/Heatmiser-for-home-assistant/stat.html)?

**Comment by Nick-Sills** [comment]
> Automations need to use a different service to set the preset rather than the hvac action. This should be easy to take care off but let me know if you need help.

Yes, that's easy to care of, and I know how to do that, but it really shouldn't be necessary. 

> A visual issue where thermostats from different integrations display different things. My suggestion here is to not rely on the standard climate entity row at all. Use something like the [multiple-entity-row](https://github.com/benct/lovelace-multiple-entity-row) and display exactly what you want.

Thanks for the head-up. I'll take a look

> Out of interest, those thermostats upstairs that are off but heating (which looks odd to my eyes), if you look at the history graph, does it show that they have been heating (eg the orange shaded area under the gr

Yes, the `havac_action` changes when the frost set-back is reached. It's set to 12c, as is the Heatmiser default, because that's also a good damp  prevention temperature.  That's the way frost protection works. When the heating is turned off, the set-back temp prevents the temp dropping lower than 12c. It isn't an `hvac_mode` heating state, and the target heating temp isn't 12c. It heats when reaching 12c, not heating to 12c, and it does this specifically when the mode is `off`.  It's quite normal and that's how thermostats work.

> Also, why do you have all but one thermostat set to away? For the heatmiser stats, just set one to away and all will go to away. No need to set each one to standby.

 I thought you might comment on that :-) I know the difference between `standby` and `away`, that was me just playing with the settings. TBH when using HA to automate things, you don't need both.

**Comment by ocrease** [comment]
> Yes, that's easy to care of, and I know how to do that, but it really shouldn't be necessary.

Shouldn't be necessary, eg you think this integration should behave differently? Climate entities are not just thermostats, from the home assistant [docs](https://developers.home-assistant.io/docs/core/entity/climate):

> A climate entity controls temperature, humidity, or fans, such as A/C systems and humidifiers

I can see how `HVACMode.OFF` would be needed by some of those types of climate entities, but I still think its correct for a thermostat that is in frost protection mode to not be `OFF`. I understand other integrations do it differently and that's their choice. Did you check the history charts? Last time I checked they didn't report heating (eg the orange shaded area) when the HVACMode is OFF, which is one of the main reasons I think it is wrong to use OFF in this case. 

> Thanks for the head-up. I'll take a look

If you need sample config, let me know


Also I found the discussion where `turn_on`/`turn_off` was added:

https://github.com/home-assistant/core/pull/11379

As you can see it was originally added for A/C climate entities, which can truly be OFF. FYI, theoretically the Heatmiser thermostats could also be fully off if the frost protection temperature is not set. In that case we would report the `hvac_action` as `off` instead of `idle`

**Comment by Nick-Sills** [comment]
> Shouldn't be necessary, eg you think this integration should behave differently? Climate entities are not just thermostats, from the home assistant [docs](https://developers.home-assistant.io/docs/core/entity/climate):

Do I think the Heatmiser integration should behave different? Not at all. However, the Heatmiser UI is atrocious, and the Neo range of sensors they are just thermostats. I just think we shouldn't follow the Heatmiser UI through in Home Assistant and recognise that 'Frost Setting' isn't a heating mode - regardless of preset. 

There are many options for me to overcome the issues, including creating virtual MQTT devices - I like doing that :-) 

Anyway, I'm honestly not going die on a hill over this, and thank you so much for the integration. It's really appreciated. 👍

**Comment by Nick-Sills** [comment]
BTW: If you're into wall displays, this is a great device from Shelly. It supports HA dashboards by URL and creates multiple entities in HA, including a Climate device, so can be used with any heating system . It's going to replace one of my Heatmiser stats and be a control panel for the rest.  I've got 2 now for different locations and plan to possibly get more to control groups. 

https://www.shelly.com/products/shelly-wall-display-x2-white-1?variant=56592799400285

**Comment by ocrease** [comment]
Ha I was going to ask if you wouldn't mind sharing what the dashboard on the shelly looks like? I am tempted by an inwall display :)

Would you be ok if we close this ticket?

**Comment by Nick-Sills** [comment]
Would you mind keeping the ticket open for a bit? I just want to see if there's any further support so I don't feel like a lone nutter. 😄

**Comment by ocrease** [comment]
Haha sure no problem

**Comment by TinyBigJacko** [comment]
> Would you mind keeping the ticket open for a bit? I just want to see if there's any further support so I don't feel like a lone nutter. 😄

At the risk of tempting your ire, I have to say I think I'm in the opposing camp, sorry!
I fully agree we shouldn't attempt to emulate all aspects of the Heatmiser Neo App (the PC version of which absolutely does my head in - mostly because it seems to randomly return different 'recipes' I've set up, which bear no correlation to my last save - but that's another story).

But the point is, I don't think we **are** proposing to 'emulate' the Heatmiser app here - it's about compliance with the HomeAssistant 'Climate' specifications, and this is where the whole confusion/misconception stems from, I think... Heat does not always mean "I am pumping out heat" (from a device's POV) or even "I am calling for heat". I can just mean "I am not in **Cooling** mode", don't forget. I believe (and please correct me if I'm wrong) that this is what's being tagged here in these displays: the ecosystem difference between **modes** of the whole Heating, Ventilation and Air Conditioning (HVAC) paradigm. Obviously us in jolly old Blighty look at the 'VAC' part of that with a mixture of envy and derision or disbelief of possibility (_at least I do, except on those four days every year when I'm struggling to keep the house below 40°C and have every window open and would give my right arm for some AC_).

I think this is the point, though - on those for days, we in Blighty don't want to be misled into thinking that our HVAC system is in 'HEAT' mode (despite the fact that it's all it can ever do), but we don't have the facility to see it in 'COOL' mode, and probably our next-best alternative (for a 'no-need-to-really-think-about-it' level of ease) is to see it in 'OFF' mode. But the reality is, our system just plain **isn't** in OFF mode; it's in HEAT mode, and always will be, unless we **really** turn it all off at source. It's in HEAT mode because it's not an HVAC system, it's a HEATing system. ;)

Really, this is an us problem, I think. We just need to recognise that 'Idle' means 'I'm in whatever mode (HEAT in this case) but doing NOTHING, so don't panic'. And Standby further reaffirms that we're not actively 'hunting' for a warm temperature, nor are we calling for or providing any actual heat. I think education of our guests and other halves and fellow house-dwellers is (and I say this knowing I place myself in great peril) at least part of the requirement here.

I guess if one thing was feasible to add, it would be the ability to suppress the announcement of the current HVAC mode from the various displays, because in places (like the UK) where only one is ever going to be be in use, most likely (except on the very latest top-of-the-range housebuilds that do have AC maybe), there's just no point in seeing something that's never going to change. But I think @ocrease has given us one way of suppressing that info, if it's really that necessary to do. Certainly I can imagine that in a house which is being AirBNBed or something, that would be really helpful in order to avoid those annoying calls (or people fiddling), because no amount of notices on the wall or in the guest docs will ever find its education target.

I feel your pain, but sadly, don't think we should be showing 'OFF', when we're in frost-protection mode and potentially **could** be ON, and actively calling for heat automatically. That certainly should NOT be missed from the HA histories, just because HA interprets OFF to mean 'definitely not worth polling until we're told otherwise'. 

It's a UI problem, really, nothing more.

**Comment by Nick-Sills** [comment]
@TinyBigJacko  Thanks for taking the time to think this through — much appreciated. I'm in the UK too, but my Heatmiser stats are in Ireland. Same ballpark, climate-wise.

> But the reality is, our system just plain isn't in OFF mode; it's in HEAT mode, and always will be, unless we really turn it all off at source. It's in HEAT mode because it's not an HVAC system, it's a HEATing system. ;)

Nope, it's "OFF" 😀 and this has nothing to do with modes available to cooling AC units, or our position in the northern hemisphere.

The point I was trying to make about 'Off' is that  other thermostats I use — including Tado here in the UK — all support an 'Off' mode as well as a frost protection setpoint. Tado, for example, has Auto, Heat, and Off modes, where Auto runs the schedule. Regardless of mode, if the room drops to the frost temp, heating kicks in. That’s true across the board — TVRs, Nest, Tado, you name it.  Sonoff TRVs have "Heat" and "Off" with frost protection when Off. **Heatmiser seems to be the odd one out in Home Assistant**, with no support for Climate On/Off/Toggle, which feels inconsistent considering there are literally hundreds of heating thermostat integrations.

> That certainly should NOT be missed from the HA histories, just because HA has interprets OFF to mean 'definitely not worth polling until we're told otherwise'.

I wouldn’t have thought polling would be an issue for Heatmiser over Wi-Fi or Ethernet. And I’m not sure I fully understand the problem with history logging — when frost protection kicks in, the current state changes from Idle to Heating, even if the mode is set to Off. That's no different to the current situation. 

Slightly off topic (so bear with me)…

I'm currently trying to build a failsafe UI that even my wife and guests can use confidently. What I’ve realized is: none of this discussion about climate 'modes' really matters for the UI unless you care about keeping automations consistent across different thermostat types. And I do. So Heatmiser being the exception kind of drives me mad — but I guess I can survive.

Also, sliding a temperature between 5c and 35c isn’t helpful for most people. That’s a UI designed by tech nerds (I include myself) who think it’s cool, but in reality, we all use a pretty narrow range. No one’s thinking in 0.5°C steps either. So I'm going back to basics — revisiting the old-school heating controller approach, but reimagining it to be intuitive and guest-friendly, with individual room control.

It's an HA dashboard on a Shelly Wall Display x2. 

<img src="https://github.com/user-attachments/assets/4eb287ca-ec0c-41ec-8c65-d28188240239" width="350" />

Boost and Economy icons change colour, but I really need to make the current state more discoverable..

It's a mixture if Heatmiser, Zigbee Sonoff TRVs and Chinese no-name ZigBee wall stats. The current operational mode of the stats is irrelevant. Heating is either On or Off - nice and simple and I'm purposefully hiding the actual room temperatures. Who cares! If your cold - hit the Boost button. 😀

**Comment by Nick-Sills** [comment]
@ocrease, @TinyBigJacko — Thanks for indulging me thus far and I’ll make one last attempt to state my case clearly.

The purpose of a room thermostat is to heat (or cool) a room to a comfortable setpoint. The purpose of a frost setback is to initiate heating at a predetermined low temperature to prevent pipes from bursting or damp forming. **These are not the same — the frost temperature isn’t a heating target.**

When a stat **isn’t** set to  heat or cool to maintain a comfort temperature, it’s in an Off state.

@TinyBigJacko — please forgive me if I’m misrepresenting your previous post, but I think the HVAC mode, geo-location, and history references highlight that I haven’t explained myself properly.

To illustrate the ‘problem’, here’s how other thermostats behave in my ecosystem. `hvac_action` changes from `idle` to `heating` when the setback temp is reached, and all have an Off state :

**Tado** – Frost protection is automatic and unchangeable
https://www.home-assistant.io/integrations/tado/

![Image](https://github.com/user-attachments/assets/17ef212d-4f4b-4626-9d34-58d0702df92c)

**Sonoff TRVZB** – Frost protection is configurable and set to the same 12°C as Heatmiser.

Note:
> Frost protection temperature (numeric)
Minimum temperature at which to automatically turn on the radiator, **if system mode is off, to prevent pipes freezing**

https://www.zigbee2mqtt.io/devices/TRVZB.html

![Image](https://github.com/user-attachments/assets/55508fc0-f5dd-44d7-9464-72de21a6bb0a)

**Tuya ZWT07** – Frost protection is configurable and also set to 12°C
https://www.zigbee2mqtt.io/devices/ZWT07.html#tuya-zwt07

![Image](https://github.com/user-attachments/assets/4aa9b0f0-57ed-425b-aa9d-88cc52b32e5b)

**PRO90Z** – This isn’t the electric underfloor version; it's used as a replacement for a broken Heatmiser Neostat. Frost protection is configurable and again set to 12°C
https://www.zigbee2mqtt.io/devices/PRO-900Z.html

![Image](https://github.com/user-attachments/assets/527a1303-153a-4111-af39-7353f6d1f2cc)

Finally, @TinyBigJacko, just to show this applies to AC units too.

**Daikin FTXM42R** — I had to simulate this, since it’s not that cold in Spain right now (though it does drop below zero in Madrid during winter):
https://www.home-assistant.io/integrations/daikin/

![Image](https://github.com/user-attachments/assets/a9f0d81c-f272-4b12-b8ff-08c04ff2b32f)

@ocrease — it’s totally fine to close this ticket if my point doesn’t land. 😊 I can create special-case automations for Heatmiser and live with it. It’s just a shame that Heatmiser ends up being a special case, especially when I don’t believe it needs to be — it seems the current implementation is simply following the Heatmiser app UI, which itself doesn’t offer an explicit Off mode.

**Comment by Nick-Sills** [comment]
**Note:** Heatmiser refers to Away and Standby as **Off**

https://faq.heatmiser.com/hc/en-us/articles/360001691420-What-is-the-Standby-Away-Temperature-setting

> Away - **Switches off** your entire system indefinitely.
> Standby- **Switches off** the zone indefinitely.

https://faq.heatmiser.com/hc/en-us/articles/360001721999-Turn-the-Heating-Off-Standby-Mode

> Turn the Heating **Off** (Standby Mode)


If the point has landed, then a possible solution could be:

Leave the preset `Away` exactly as it is now. It’s largely irrelevant in Home Assistant, since you can easily achieve the same effect by automating all stats to Standby.

Add back the `hvac_mode off`, and sync it with the `Standby` preset. Syncing with `Standby` means that individual stats can be switched off with `climate.turn_off`

This way, all existing preset-based automations continue to work exactly as before, and we gain support for `climate.turn_on`, `climate.turn_off`, and `climate.toggle` actions, and “Heat” is no longer  a constant static string in the UI - just like all other heating stats. 

Apologies for the many posts and all the text — I just wanted to make sure my concern was clearly understood before a decision was made to close this issue. 🤞

**Comment by TinyBigJacko** [comment]
@Nick-Sills Thanks for all that clarification. I'll be honest, it took me a while to fully see what you're getting at, and I'm beginning to lean back towards your way of thinking. This does all seem to be, at its root, a different interpretation by Heatmiser, versus others in the same field.

Perhaps the issue is as simple as having '**heat**' and '**off**' being **hvac_modes**, while '**standby**' is simply a **preset** (which places the individual stat into off-with-frost-protection mode, but ultimately, given the way Heatmiser works, does not change the overall hvac_mode to off, unless all the stats are in standby mode - which is, in effect, **away** mode for the entire system).

I'm wavering, I know, and I apologise for a somewhat 'limited to Heatmiser world view' - because that's all I have experience of in my house, and my relatively recent journey in HA. You've clearly got a wider perspective, given the other systems you've encountered, and that's valuable info, for sure. My predilection is obviously for 'something that maps to what my system already displays', but conformity is going to be sensible, without doubt.

How do the other stats and heating/HVAC systems you've encountered deal with the specific situation of **individual stats** being 'off' (with or without frost-protection) on a per room basis, versus the entire system itself being off (as in 'fully off'). How do they differentiate - if even they do - between the two nuances?

I do fully accept that the display of the word 'HEAT' on a GUI is very likely to be confusing to guests who aren't the owners, and are not on holiday to learn about a heating system's idiosyncrasies, and are likely to start messing untowardly with something if they think it is fired up and burning, when it actually isn't, and they don't want it to be.

It's another thing entirely, convincing family members to 'get with the program' and make allowances for confusing displays that can be learned and re-taught... but guests are going to be an endless treadmill of blank slates, I can see... and sympathise!

**Comment by Nick-Sills** [comment]
@TinyBigJacko — thanks for responding and thinking this through!

> How do the other stats and heating/HVAC systems you've encountered deal with the specific situation of individual stats being 'off' (with or without frost-protection) on a per room basis, versus the entire system itself being off (as in 'fully off'). How do they differentiate - if even they do - between the two nuances?

Heatmiser has really muddled the implementation with 'Away' and 'Standby', and also by displaying a 'Frost' symbol both in the app and on their stats when the setback temp is 12°C. I’ll do my best to explain why I think their implementation is half-baked — and how Tado (and others) have got it right.

Tado has two presets: 'Home' and 'Away'. Crucially, there’s a specific 'Away' temperature that can be configured — and it’s not the same as the frost protection temperature. Like Heatmiser, setting 'Away' turns all stats to the Away temperature. However, turning individual stats off puts them into a frost protection state — which is a fixed standby temperature (I believe it’s 5°C). This frost setting is not configurable, and you can't disable it.

Sonoff, on the other hand, has a configurable frost temperature, 4°C to 35°C, that’s used when individual stats are turned off. There’s no system-wide control to apply this state across all stats.

Daikin is similar — when an AC unit is turned 'off', a configurable frost protection temperature (somewhere between 5°C and 16°C, I think) is activated. Again, this operates on a per-stat basis. There's no system-wide setting in Home Assistant, although the Daikin app does offer a 'Holiday' mode that turns off all stats.

> Perhaps the issue is as simple as having 'heat' and 'off' being hvac_modes, while 'standby' is simply a preset (which places the individual stat into off-with-frost-protection mode, but ultimately, given the way Heatmiser works, does not change the overall hvac_mode to off, unless all the stats are in standby mode - which is, in effect, away mode for the entire system).

Not quite. I think it should be 'Heat' and 'Off' as the `hvac_modes`, with 'Away' being a preset. 'Away' is a Heatmiser app construct that simply sets all stats into the 'Standby' state, but shows as 'Away' in the UI.

The main advantage of syncing 'Off' with 'Standby' is that it lets you control individual stats by turning them off — which puts them into frost protection mode. 'Away', on the other hand, affects every stat, and isn’t especially useful in Home Assistant, since you can easily automate putting all stats into 'Standby' — which is functionally identical to 'Away' anyway.

So, to be operationally consistent with all other thermostats in Home Assistant:



Home Assistant Action | Description
-- | --
`climate.turn_on` | Sets the stat preset to 'Home' and sets the `hvac_mode` to 'heat'.
`climate.turn_off` | Sets the Heatmiser stat preset to 'Standby' and sets the hvac_mode to 'off'. This could remain a preset in Home Assistant, or the preset label could be dropped from the UI — as long as 'off' is synced with 'Standby' on the Heatmiser controller.
`climate.set_preset_mode` to 'Away' | Behaves as it does now.

This makes everything behave like other thermostats, and also ensures that any existing Heatmiser automations continue to work as before — as long as we keep 'Standby' as a preset rather than removing it.

I hope that makes sense, and that I haven't missed something crucial in the integration implementation. 

As I mentioned, I can work around the way this works at the moment, but I'm a bit obsessive on consistency and useability. 😄

**Comment by dmccaffery** [comment]
One thing that I noticed is that this error being thrown makes it impossible to use the stat in a scene since all settings set on the device are set when applying the scene. Home Assistant attempts to set the hvac_mode, this error is thrown, and other settings are then ignored:

https://github.com/MindrustUK/Heatmiser-for-home-assistant/blob/fead1bda43ce71af55899a90092add8f6a0bbe25/custom_components/heatmiserneo/climate.py#L258

See the error when applying the scene:

![Image](https://github.com/user-attachments/assets/34b77d70-5434-416f-9a13-5154b195bbc6)

This can easily be worked around using automations, but thought I would point this out.

Can we change this to a log entry and return vs raising an error? I'm happy to put in the PR to achieve this if agreed.

**Comment by ocrease** [comment]
@dmccaffery as far as I'm aware, a future (but soon) HA release will raise an error anyway of you try to set an invalid hvac_mode, so not sure changing the error would work for long.

I don't have any experience with scenes. Can. You share the scene definition (I assume in yaml) so I can try it out and see what can be done?

@Nick-Sills @TinyBigJacko thanks for your contributions. I haven't forgotten you, I just haven't had time to digest everything you've written!

**Comment by dmccaffery** [comment]
Here you go:

Note that the visual editor sets every attribute of every entity of the device added to a scene based on the config set via UI. I could edit the yaml and remove the hvac_mode as a workaround, but that's not a great experience for those that only use the visual editor. There is no way to not set the hvac mode visually as it's the only option in the select.

```yaml
id: "1744968104305"
name: Turn Off Heating
entities:
  climate.conservatory_heating:
    hvac_modes:
      - heat
    min_temp: 5
    max_temp: 35
    target_temp_step: 0.5
    preset_modes:
      - home
      - boost
      - away
      - standby
    current_temperature: 21.5
    temperature: 8
    hvac_action: idle
    preset_mode: standby
    device_type: 1
    low_battery: false
    offline: false
    standby: true
    hold_on: false
    hold_time: "0:00"
    hold_temp: 21
    floor_temperature: 127.5
    preheat_active: false
    hc_mode: HEATING
    sensor_mode: BUILT_IN
    icon: mdi:heating-coil
    friendly_name: Conservatory Heating
    supported_features: 17
    state: heat
  select.conservatory_heating_active_profile:
    options:
      - PROFILE_0
      - Winter
    device_id: 3
    device_type: 1
    offline: false
    friendly_name: Conservatory Heating Active Profile
    state: Winter
  lock.conservatory_heating_lock:
    device_id: 3
    device_type: 1
    offline: false
    friendly_name: Conservatory Heating Lock
    supported_features: 0
    state: locked
icon: mdi:radiator-off
metadata: {}
```

**Comment by ocrease** [comment]
@dmccaffery I created a new issue #281 based on what you reported.

**Comment by ocrease** [comment]
@Nick-Sills @TinyBigJacko I have read all your comments again and I'm afraid I remain unconvinced. Here are the main points raised:

- The display on the entities row shows "Heat" - I already suggested an alternative that you could use to make sure all your thermostats look the same. Alternatively you could raise an issue with HA itself so that the hvac_mode (eg Heat) is not shown if there is only one hvac_mode supported. 
- Other integrations have an `Off` hvac mode. I can understand an AC unit (eg cool only, not like the Daikin unit you have which I assume can do heating and cooling) having an Off mode, eg no matter what happens it won't start cooling. The climate entity has to support many types of devices, so having the ability to support Off is necessary. But for thermostats, specially ones with frost protection, they are simply never Off (unless you cut the power, but that's not something you can control via this integration!). Remember there is an `hvac_mode` (always heat) and an `hvac_action` which tells you what the thermostat is currently doing. In standby, the mode will be heat and the action will be idle (or off if the frost protection is disabled) or heating if the frost protection kicked in. The thermostat is not off, it is idle.
- Recreating the Heatmiser UI - The aim is not to recreate the Heatmiser UI, but to expose as much functionality as possible. Different users will have different use cases and requirements, so the more functionality that can be exposed the better.
- Tado has 'Home' and 'Away' and away has a configurable temperature - If you want something like this I would suggest using different profiles, so you have a home profile and an away profile which has a setback temperature that is much higher than the frost protection temperature.
- Frost protection is not a target temperature - this one you may have a point, but its pretty minor and out of all thermostat brands out there, I'm sure some will trigger at the frost protection temperature and others will trigger when you are sufficiently below the frost protection temperature. Its too warm at the moment for me to confirm what my heatmiser stats do. But either way it is minor, if frost protection kicks in, hopefully no-one is in the property!
- Inconsistencies between automations required for each integrations - I can see how this is annoying, but also very easy to solve in HA.

Also, most of your screenshots in https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/280#issuecomment-2746127404 look odd. Tado says the set temp is 2, the current temp is 20 but the hvac_action is heating?! The Sonoff and PRO90Z show similar strange behaviour (current temp above set temp and it reports as heating)

> It's another thing entirely, convincing family members to 'get with the program' and make allowances for confusing displays that can be learned and re-taught... but guests are going to be an endless treadmill of blank slates, I can see... and sympathise!

If the display is confusing to any of the users, change the display! The beauty of HA is that you can customize it exactly how you want.

I'll keep this open for now in case  someone else wants to contribute to the discussion, but so far I don't see a reason to re-introduce the OFF hvac_mode

**Comment by Nick-Sills** [comment]
@ocrease Thanks for the reply, and for your consideration in leaving this issue open.

I understand that the UI quirks and automation challenges in Home Assistant can be worked around. The real issue is that every other thermostat exposes standard `Off` and `Heat` modes, Heatmiser is the exception. The argument that Heatmiser stats are never truly "off" due to frost protection doesn't hold up, since all other thermostats also include frost protection and still provide a proper Off mode.

This inconsistency only becomes a problem when you mix Heatmiser with other stats, or if you use integrations that rely on `climate.turn_off`. The issue with scenes seems to be a symptom of this same underlying mismatch.

In my case, I've managed to work around it, but it's been a real pain and makes ongoing maintenance a problem. I now have a fairly comprehensive heating control setup with both Heatmiser and non-Heatmiser stats. The package is over 1,000 lines of YAML, and a significant chunk of that is just handling Heatmiser-specific exceptions. 

A single automation example below, but there are many others in my setup:

 ```yaml
 - id: ch_control_guest_override_sets_occupancy
    alias: "CH Control - Guest Override Sets Occupancy"
    trigger:
      #### Heatmiser exception logic: these thermostats report preset_mode == 'home' when manually turned on ###
      - platform: state
        entity_id:
          - climate.bedroom_downstairs
          - climate.kitchen
          - climate.utility
          - climate.dining_room
          - climate.living_room
          - climate.study
        attribute: preset_mode
        to: "home"

      # All other stats use state == 'heat' for manual overrides
      - platform: state
        entity_id:
          - climate.cong_hallway_master
          - climate.cong_room_thermostat
          - climate.cong_trv_back_bedroom
          - climate.cong_trv_front_bedroom
          - climate.cong_trv_middle_bedroom
        to: "heat"
    action:
      - variables:
          thermostat_to_room_map:
            climate.bedroom_downstairs: input_boolean.occupied_bedroom_downstairs
            climate.kitchen: input_boolean.occupied_kitchen
            climate.utility: input_boolean.occupied_utility
            climate.dining_room: input_boolean.occupied_dining_room
            climate.living_room: input_boolean.occupied_living_room
            climate.study: input_boolean.occupied_study
            climate.cong_hallway_master: input_boolean.occupied_hallway
            climate.cong_room_thermostat: input_boolean.occupied_main_bedroom
            climate.cong_trv_back_bedroom: input_boolean.occupied_back_bedroom
            climate.cong_trv_front_bedroom: input_boolean.occupied_front_bedroom
            climate.cong_trv_middle_bedroom: input_boolean.occupied_middle_bedroom
          room_boolean: "{{ thermostat_to_room_map[trigger.entity_id] }}"

      - choose:
          - conditions:
              - condition: template
                value_template: "{{ is_state(room_boolean, 'off') }}"
            sequence:
              - service: input_boolean.turn_on
                target:
                  entity_id: "{{ room_boolean }}"
              - service: logbook.log
                data:
                  name: "CH Override"
                  message: "Guest override: {{ trigger.entity_id }} manually turned on — setting {{ room_boolean }} to occupied."
                  entity_id: "{{ trigger.entity_id }}"

      - choose:
          - conditions:
              - condition: state
                entity_id: switch.derries_occupied_switch
                state: "off"
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: switch.derries_occupied_switch
              - service: logbook.log
                data:
                  name: "CH Override"
                  message: "Guest override: Activating main occupied switch due to manual stat change on {{ trigger.entity_id }}."
                  entity_id: switch.derries_occupied_switch

    mode: queued
```


Again, thanks for leaving this open 😄 . I suspect there will be others who chime in if they have a mixture of stats and/or use other heating customizations or integrations that expect `climate_turn_off`
