### ISSUE TITLE
heatmiserneo.hold_on - Unknown Action

### ISSUE THREAD

**Issue by cjoha** [MindrustUK/Heatmiser-for-home-assistant#290]
Hi there,

I have a Heatmiser neo system, with the neostat hub. I've one main automation which triggers the thermostats to hold a lower temperature for a specified duration of time. This is because we hit peak electricity rates, and I want to hold the stats down so they don't call for heat from the heatpump, unless the outside temp is below 10 degrees C.

I've recently noticed an error in HomeAssistant stating that this heatmiserneo.hold_on is an "Unknown Action", even though its shown in the list of actions for the integration. Below is my automation. I think the issue relates to the hold down temperature not being specified, but I'm not sure. I'm fairly sure this has worked in the past, but recent updates might have broken it?

```
alias: Thermostats - Peak Energy - Hold Down
description: ""
triggers:
  - trigger: time
    at: "17:00:00"
conditions:
  - condition: numeric_state
    entity_id: weather.pirateweather
    above: 10
    attribute: temperature
actions:
  - action: heatmiserneo.timer_hold_on
    metadata: {}
    data:
      hold_duration:
        hours: 2
        minutes: 0
        seconds: 0
      hold_state: true
    target:
      entity_id:
        - select.hallway_active_profile
        - select.kitchen_active_profile
        - select.lounge_active_profile
        - select.master_bedroom_active_profile
        - select.playroom_active_profile
mode: single
```

**Comment by ocrease** [comment]
Hi @cjoha, I notice two things:

- You are using `heatmiserneo.timer_hold_on`, but you should be using `heatmiserneo.hold_on` which is for thermostat devices and allows setting the temperature
- Your target entities are the active profile select entity. I think you should use the climate entity itself, eg `climate.kitchen`

Take a look at https://mindrustuk.github.io/Heatmiser-for-home-assistant/services.html

**Comment by cjoha** [comment]
Thanks, I hadn't spotted that. I have both changed, but now I'm getting an error on the Action object. Any help would be really appreciated.

Error:
The automation "Thermostats - Peak Energy - Hold Down" (automation.thermostats_peak_energy_hold_down) has an unknown action: heatmiserneo.hold_on.

Automation YAML:
```
alias: Thermostats - Temp Hold Down at Peak
description: ""
triggers:
  - trigger: time
    at: "17:00:00"
conditions:
  - condition: numeric_state
    entity_id: weather.pirateweather
    attribute: temperature
    above: 10
actions:
  - action: heatmiserneo.hold_on
    metadata: {}
    data:
      hold_duration:
        hours: 2
        minutes: 0
        seconds: 0
      hold_temperature: 15
    target:
      entity_id:
        - climate.hallway
        - climate.kitchen
        - climate.lounge
        - climate.master_bedroom
        - climate.playroom
mode: single
```
